# Generated by Django 4.1 on 2022-09-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.CharField(max_length=225)),
                ('title', models.TextField()),
                ('rating', models.TextField()),
                ('release_date', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='myWatchList',
        ),
    ]
