# Generated by Django 4.1 on 2022-09-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_watchlist_rating_alter_watchlist_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='release_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watched',
            field=models.CharField(max_length=25),
        ),
    ]
