# Generated by Django 4.1 on 2022-09-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_watchlist_rating_alter_watchlist_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
